#include "ukf_config_params.h"

#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

int hls_SR_UKF(const float x0[UKF_N], const float z_seq[UKF_STEPS * UKF_M], float x_seq[UKF_STEPS * UKF_N],
               float S_upper_seq[UKF_STEPS * 6]);

static bool starts_with(const std::string& s, const std::string& p) {
  return s.size() >= p.size() && s.compare(0, p.size(), p) == 0;
}

static std::string trim(const std::string& s) {
  size_t b = 0;
  while (b < s.size() && (s[b] == ' ' || s[b] == '\t' || s[b] == '\r' || s[b] == '\n')) {
    ++b;
  }
  size_t e = s.size();
  while (e > b && (s[e - 1] == ' ' || s[e - 1] == '\t' || s[e - 1] == '\r' || s[e - 1] == '\n')) {
    --e;
  }
  return s.substr(b, e - b);
}

static int parse_input(const char* path, int& N, float x0[UKF_N], float sV[UKF_N][UKF_STEPS],
                       float z_seq[UKF_STEPS * UKF_M]) {
  std::ifstream fin(path);
  if (!fin) {
    return 1;
  }

  bool haveN = false;
  bool havex0 = false;
  int rowCount = 0;

  std::string line;
  while (std::getline(fin, line)) {
    line = trim(line);
    if (line.empty() || line[0] == '#') {
      continue;
    }

    if (starts_with(line, "N ")) {
      std::istringstream iss(line);
      char c0;
      iss >> c0 >> N;
      if (!iss || c0 != 'N') {
        return 2;
      }
      haveN = true;
      continue;
    }

    if (starts_with(line, "x0 ")) {
      std::istringstream iss(line);
      std::string tag;
      iss >> tag;
      for (int i = 0; i < UKF_N; ++i) {
        double v;
        iss >> v;
        if (!iss) {
          return 3;
        }
        x0[i] = static_cast<float>(v);
      }
      havex0 = true;
      continue;
    }

    std::istringstream iss(line);
    int k;
    double s1, s2, s3, z1, z2;
    iss >> k >> s1 >> s2 >> s3 >> z1 >> z2;
    if (!iss) {
      return 4;
    }
    if (rowCount >= UKF_STEPS) {
      return 5;
    }
    if (k != rowCount + 1) {
      return 6;
    }

    sV[0][rowCount] = static_cast<float>(s1);
    sV[1][rowCount] = static_cast<float>(s2);
    sV[2][rowCount] = static_cast<float>(s3);

    z_seq[rowCount * UKF_M + 0] = static_cast<float>(z1);
    z_seq[rowCount * UKF_M + 1] = static_cast<float>(z2);

    ++rowCount;
  }

  if (!haveN || !havex0) {
    return 7;
  }
  if (N != UKF_STEPS) {
    return 8;
  }
  if (rowCount != UKF_STEPS) {
    return 9;
  }
  return 0;
}

static int write_output(const char* path, int N, const float z_seq[UKF_STEPS * UKF_M], const float x_seq[UKF_STEPS * UKF_N],
                        const float S_upper_seq[UKF_STEPS * 6]) {
  std::ofstream fout(path);
  if (!fout) {
    return 1;
  }

  fout << "# ukf_output.txt\n";
  fout << "# Generated by ukf_tb.cpp (Vitis HLS csim)\n";
  fout << "# Input file: ukf_input.txt\n";
  fout << "# Dimensions: n=" << UKF_N << ", m=" << UKF_M << "\n";
  fout << "# Noise std: q=" << std::setprecision(17) << UKF_Q_STD << ", r=" << std::setprecision(17) << UKF_R_STD << "\n";
  fout << "N " << N << "\n";
  fout << "# rows: k z1 z2 x1 x2 x3 S11 S12 S13 S22 S23 S33\n";

  fout.setf(std::ios::fmtflags(0), std::ios::floatfield);
  fout << std::setprecision(17);

  for (int k = 0; k < N; ++k) {
    const float z1 = z_seq[k * UKF_M + 0];
    const float z2 = z_seq[k * UKF_M + 1];
    const float x1 = x_seq[k * UKF_N + 0];
    const float x2 = x_seq[k * UKF_N + 1];
    const float x3 = x_seq[k * UKF_N + 2];

    const float S11 = S_upper_seq[k * 6 + 0];
    const float S12 = S_upper_seq[k * 6 + 1];
    const float S13 = S_upper_seq[k * 6 + 2];
    const float S22 = S_upper_seq[k * 6 + 3];
    const float S23 = S_upper_seq[k * 6 + 4];
    const float S33 = S_upper_seq[k * 6 + 5];

    fout << (k + 1) << " " << z1 << " " << z2 << " " << x1 << " " << x2 << " " << x3 << " " << S11 << " " << S12
         << " " << S13 << " " << S22 << " " << S23 << " " << S33 << "\n";
  }
  return 0;
}

static int write_plot_png(const char* path, int N, const float sV[UKF_N][UKF_STEPS], const float x_seq[UKF_STEPS * UKF_N]) {
  FILE* gp = popen("gnuplot", "w");
  if (!gp) {
    return 1;
  }

  std::fprintf(gp, "set terminal pngcairo size 900,900\n");
  std::fprintf(gp, "set output '%s'\n", path);
  std::fprintf(gp, "set multiplot layout 3,1\n");
  std::fprintf(gp, "set key off\n");
  std::fprintf(gp, "set grid\n");

  for (int i = 0; i < UKF_N; ++i) {
    std::fprintf(gp, "plot '-' with lines lt 1 lw 2, '-' with lines lt 2 dt 2 lw 2\n");
    for (int k = 0; k < N; ++k) {
      std::fprintf(gp, "%d %.17g\n", k + 1, static_cast<double>(sV[i][k]));
    }
    std::fprintf(gp, "e\n");
    for (int k = 0; k < N; ++k) {
      std::fprintf(gp, "%d %.17g\n", k + 1, static_cast<double>(x_seq[k * UKF_N + i]));
    }
    std::fprintf(gp, "e\n");
  }

  std::fprintf(gp, "unset multiplot\n");
  std::fprintf(gp, "set output\n");
  std::fflush(gp);
  const int rc = pclose(gp);
  return (rc == 0) ? 0 : 2;
}

static bool is_finite_f(float v) {
  return std::isfinite(static_cast<double>(v)) != 0;
}

static int error_check(int N, const float z_seq[UKF_STEPS * UKF_M], const float x_seq[UKF_STEPS * UKF_N],
                       const float S_upper_seq[UKF_STEPS * 6]) {
  double se_z[UKF_M] = {0.0, 0.0};
  double maxae_z[UKF_M] = {0.0, 0.0};

  for (int k = 0; k < N; ++k) {
    const float z1 = z_seq[k * UKF_M + 0];
    const float z2 = z_seq[k * UKF_M + 1];
    const float x1 = x_seq[k * UKF_N + 0];
    const float x2 = x_seq[k * UKF_N + 1];
    const float x3 = x_seq[k * UKF_N + 2];

    if (!is_finite_f(z1) || !is_finite_f(z2) || !is_finite_f(x1) || !is_finite_f(x2) || !is_finite_f(x3)) {
      return 101;
    }

    const float S11 = S_upper_seq[k * 6 + 0];
    const float S22 = S_upper_seq[k * 6 + 3];
    const float S33 = S_upper_seq[k * 6 + 5];
    if (!is_finite_f(S11) || !is_finite_f(S22) || !is_finite_f(S33) || !(S11 > 0) || !(S22 > 0) || !(S33 > 0)) {
      return 102;
    }

    const double e1 = static_cast<double>(x1) - static_cast<double>(z1);
    const double e2 = static_cast<double>(x2) - static_cast<double>(z2);
    se_z[0] += e1 * e1;
    se_z[1] += e2 * e2;
    if (std::fabs(e1) > maxae_z[0]) {
      maxae_z[0] = std::fabs(e1);
    }
    if (std::fabs(e2) > maxae_z[1]) {
      maxae_z[1] = std::fabs(e2);
    }
  }

  const double rmse_z1 = std::sqrt(se_z[0] / static_cast<double>(N));
  const double rmse_z2 = std::sqrt(se_z[1] / static_cast<double>(N));

  constexpr double RMSE_Z_THRESH = 0.2;
  constexpr double MAXAE_Z_THRESH = 0.6;

  std::cout << std::setprecision(17);
  std::cout << "errorcheck: rmse(x1-z1)=" << rmse_z1 << " rmse(x2-z2)=" << rmse_z2 << "\n";
  std::cout << "errorcheck: maxae(x1-z1)=" << maxae_z[0] << " maxae(x2-z2)=" << maxae_z[1] << "\n";

  if (rmse_z1 > RMSE_Z_THRESH || rmse_z2 > RMSE_Z_THRESH || maxae_z[0] > MAXAE_Z_THRESH || maxae_z[1] > MAXAE_Z_THRESH) {
    return 103;
  }
  return 0;
}

int main() {
  int N = 0;
  float x0[UKF_N];
  float sV[UKF_N][UKF_STEPS];
  float z_seq[UKF_STEPS * UKF_M];
  const char* out_txt_path = "/home/whp/Desktop/XLab/UKF_Experiment/UKF2HLS/ukf_output.txt";
  const char* out_png_path = "/home/whp/Desktop/XLab/UKF_Experiment/UKF2HLS/ukf_state_compare.png";

  const int in_rc =
      parse_input("/home/whp/Desktop/XLab/UKF_Experiment/UKF_Math/ukf_input.txt", N, x0, sV, z_seq);
  if (in_rc != 0) {
    std::cerr << "failed to parse ukf_input.txt, rc=" << in_rc << "\n";
    return 1;
  }

  float x_seq[UKF_STEPS * UKF_N];
  float S_upper_seq[UKF_STEPS * 6];
  const int kern_rc = hls_SR_UKF(x0, z_seq, x_seq, S_upper_seq);
  if (kern_rc != 0) {
    std::cerr << "kernel returned rc=" << kern_rc << "\n";
    return 2;
  }

  const int out_rc = write_output(out_txt_path, N, z_seq, x_seq, S_upper_seq);
  if (out_rc != 0) {
    std::cerr << "failed to write ukf_output.txt, rc=" << out_rc << "\n";
    return 3;
  }

  const int plot_rc = write_plot_png(out_png_path, N, sV, x_seq);
  if (plot_rc != 0) {
    std::cerr << "failed to generate ukf_state_compare.png, rc=" << plot_rc << "\n";
    return 4;
  }

  const int chk_rc = error_check(N, z_seq, x_seq, S_upper_seq);
  if (chk_rc != 0) {
    std::cerr << "TEST FAIL: errorcheck rc=" << chk_rc << "\n";
    return 5;
  }
  std::cout << "TEST PASS\n";

  return 0;
}
